server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  application:
    name: mcp-server
  ai:
    mcp:
      server:
        name: mcp-server
        version: 1.0.0

blog:
  api:
    url: https://shelly.org.cn
    token: 863-4990-b55d-5b5366
